"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 4.2.30.
"""

import os
from pathlib import Path
from dotenv import load_dotenv


# ============================================================
# BASE DIRECTORY
# ============================================================

BASE_DIR = Path(__file__).resolve().parent.parent


# ============================================================
# ENVIRONMENT VARIABLES
# ============================================================

load_dotenv(dotenv_path=BASE_DIR / ".env")


# ============================================================
# SECURITY
# ============================================================

SECRET_KEY = os.getenv("SECRET_KEY")

DEBUG = os.getenv("DEBUG", "True").lower() == "true"

ALLOWED_HOSTS = [
    "localhost",
    "127.0.0.1",
]


# ============================================================
# APPLICATIONS
# ============================================================

INSTALLED_APPS = [
    # Django
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",

    # Third-party
    "corsheaders",
    "rest_framework",
    "rest_framework_simplejwt",
    "rest_framework_simplejwt.token_blacklist",

    # Project apps
    "users",
    "core",
    "products",
    "wishlist",
    "cart",
    "orders",
    "riders",
    "reviews",
]


# ============================================================
# CUSTOM USER MODEL
# ============================================================

AUTH_USER_MODEL = "users.User"


# ============================================================
# MIDDLEWARE
# ============================================================

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",

    # CORS
    "corsheaders.middleware.CorsMiddleware",

    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]


# ============================================================
# URL CONFIGURATION
# ============================================================

ROOT_URLCONF = "config.urls"


# ============================================================
# TEMPLATES
# ============================================================

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]


# ============================================================
# WSGI
# ============================================================

WSGI_APPLICATION = "config.wsgi.application"


# ============================================================
# DATABASE
# ============================================================

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.postgresql",
        "NAME": os.getenv("DB_NAME"),
        "USER": os.getenv("DB_USER"),
        "PASSWORD": os.getenv("DB_PASSWORD"),
        "HOST": os.getenv("DB_HOST", "localhost"),
        "PORT": os.getenv("DB_PORT", "5432"),
    }
}


# ============================================================
# DJANGO REST FRAMEWORK
# ============================================================

REST_FRAMEWORK = {
    "DEFAULT_AUTHENTICATION_CLASSES": [
        "users.authentication.CookieJWTAuthentication",
    ],
}


# ============================================================
# JWT COOKIE CONFIGURATION
# ============================================================

AUTH_COOKIE_ACCESS = "access_token"
AUTH_COOKIE_REFRESH = "refresh_token"

# CSRF cookie must be readable by JavaScript if your frontend
# sends the CSRF token manually.
CSRF_COOKIE_HTTPONLY = False

# Local development is running on HTTP.
AUTH_COOKIE_SECURE = False

# Suitable for localhost development.
AUTH_COOKIE_SAMESITE = "Lax"


# ============================================================
# CORS CONFIGURATION
# ============================================================

CORS_ALLOWED_ORIGINS = [
    "http://localhost:5173",
    "http://localhost:3000",
]

CORS_ALLOW_CREDENTIALS = True


# ============================================================
# CSRF TRUSTED ORIGINS
# ============================================================

CSRF_TRUSTED_ORIGINS = [
    "http://localhost:5173",
    "http://localhost:3000",
]


# ============================================================
# EMAIL
# ============================================================

# Development:
# Emails are printed in the Django terminal instead of being
# actually sent.
EMAIL_BACKEND = (
    "django.core.mail.backends.console.EmailBackend"
)


# ============================================================
# IMAGEKIT CONFIGURATION
# ============================================================

IMAGEKIT_PRIVATE_KEY = os.getenv(
    "IMAGEKIT_PRIVATE_KEY"
)

IMAGEKIT_PUBLIC_KEY = os.getenv(
    "IMAGEKIT_PUBLIC_KEY"
)

IMAGEKIT_URL_ENDPOINT = os.getenv(
    "IMAGEKIT_URL_ENDPOINT"
)


# ============================================================
# ESEWA CONFIGURATION
# ============================================================

ESEWA_SETTINGS = {
    "PRODUCT_CODE": os.getenv(
        "ESEWA_PRODUCT_CODE"
    ),

    "SECRET_KEY": os.getenv(
        "ESEWA_SECRET_KEY"
    ),

    "INITIATE_URL": os.getenv(
        "ESEWA_INITIATE_URL"
    ),

    "STATUS_CHECK_URL": os.getenv(
        "ESEWA_STATUS_CHECK_URL"
    ),

    "SUCCESS_URL": os.getenv(
        "ESEWA_SUCCESS_URL"
    ),

    "FAILURE_URL": os.getenv(
        "ESEWA_FAILURE_URL"
    ),

    "FRONTEND_ORDER_URL": os.getenv(
        "ESEWA_FRONTEND_ORDER_URL"
    ),
}


# ============================================================
# ESEWA DEBUG
# ============================================================

print("========== ESEWA DEBUG ==========")

print(
    "ESEWA PRODUCT CODE:",
    ESEWA_SETTINGS["PRODUCT_CODE"]
)

print(
    "ESEWA SECRET KEY LOADED:",
    bool(ESEWA_SETTINGS["SECRET_KEY"])
)

print(
    "ESEWA INITIATE URL:",
    ESEWA_SETTINGS["INITIATE_URL"]
)

print(
    "ESEWA STATUS URL:",
    ESEWA_SETTINGS["STATUS_CHECK_URL"]
)

print(
    "ESEWA SUCCESS URL:",
    ESEWA_SETTINGS["SUCCESS_URL"]
)

print(
    "ESEWA FAILURE URL:",
    ESEWA_SETTINGS["FAILURE_URL"]
)

print("=================================")


# ============================================================
# PASSWORD VALIDATION
# ============================================================

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME":
            "django.contrib.auth.password_validation."
            "UserAttributeSimilarityValidator",
    },
    {
        "NAME":
            "django.contrib.auth.password_validation."
            "MinimumLengthValidator",
    },
    {
        "NAME":
            "django.contrib.auth.password_validation."
            "CommonPasswordValidator",
    },
    {
        "NAME":
            "django.contrib.auth.password_validation."
            "NumericPasswordValidator",
    },
]


# ============================================================
# INTERNATIONALIZATION
# ============================================================

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# ============================================================
# STATIC FILES
# ============================================================

STATIC_URL = "static/"


# ============================================================
# DEFAULT PRIMARY KEY
# ============================================================

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"