from decimal import Decimal

from django.core.validators import MinValueValidator
from django.db import models

from products.models import Product
from users.models import CustomerProfile


class Order(models.Model):

    STATUS_CHOICES = [
        ("pending", "Pending"),
        ("packaging", "Packaging"),
        ("rider_assigned", "Rider Assigned"),
        ("out_for_delivery", "Out for Delivery"),
        ("delivered", "Delivered"),
        ("cancelled", "Cancelled"),
    ]

    PAYMENT_CHOICES = [
        ("cod", "Cash on Delivery"),
        ("esewa", "eSewa"),
    ]

    PAYMENT_STATUS_CHOICES = [
        ("pending", "Pending"),
        ("paid", "Paid"),
        ("failed", "Failed"),
    ]

    customer = models.ForeignKey(
        CustomerProfile,
        on_delete=models.CASCADE,
        related_name="orders",
    )

    assigned_rider = models.ForeignKey(
        "riders.RiderProfile",
        on_delete=models.SET_NULL,
        null=True,
        blank=True,
        related_name="assigned_orders",
    )

    # ---------------------------------------------------------
    # ORDER STATUS
    # ---------------------------------------------------------

    status = models.CharField(
        max_length=20,
        choices=STATUS_CHOICES,
        default="pending",
    )

    # ---------------------------------------------------------
    # PAYMENT
    # ---------------------------------------------------------

    payment_method = models.CharField(
        max_length=10,
        choices=PAYMENT_CHOICES,
        default="cod",
    )

    payment_status = models.CharField(
        max_length=10,
        choices=PAYMENT_STATUS_CHOICES,
        default="pending",
    )

    # eSewa transaction UUID.
    #
    # This is generated by HAAT and sent to eSewa.
    # The same UUID is used when verifying the payment.
    transaction_uuid = models.CharField(
        max_length=100,
        unique=True,
        null=True,
        blank=True,
    )

    # eSewa reference/transaction code returned after
    # successful payment verification.
    transaction_code = models.CharField(
        max_length=100,
        blank=True,
        default="",
    )

    # ---------------------------------------------------------
    # DELIVERY SNAPSHOT
    # ---------------------------------------------------------

    delivery_phone = models.CharField(
        max_length=15,
        blank=True,
        default="",
    )

    delivery_address = models.TextField(
        blank=True,
        default="",
    )

    # ---------------------------------------------------------
    # ORDER TOTAL
    # ---------------------------------------------------------

    total_price = models.DecimalField(
        max_digits=10,
        decimal_places=2,
        default=Decimal("0.00"),
    )

    # ---------------------------------------------------------
    # TIMESTAMPS
    # ---------------------------------------------------------

    created_at = models.DateTimeField(
        auto_now_add=True,
    )

    updated_at = models.DateTimeField(
        auto_now=True,
    )

    class Meta:
        ordering = ["-created_at"]

        indexes = [
            models.Index(
                fields=["customer", "-created_at"]
            ),
            models.Index(
                fields=["payment_status"]
            ),
            models.Index(
                fields=["payment_method", "payment_status"]
            ),
        ]

    def recalculate_total(self):

        total = sum(
            (
                item.subtotal()
                for item in self.items.all()
            ),
            Decimal("0.00"),
        )

        self.total_price = total

        self.save(
            update_fields=["total_price"]
        )

    def __str__(self):

        return (
            f"Order #{self.id} — "
            f"{self.customer.user.username} "
            f"({self.status})"
        )


class OrderItem(models.Model):

    order = models.ForeignKey(
        Order,
        on_delete=models.CASCADE,
        related_name="items",
    )

    product = models.ForeignKey(
        Product,
        on_delete=models.SET_NULL,
        null=True,
        related_name="order_items",
    )

    # ---------------------------------------------------------
    # PRODUCT SNAPSHOT
    # ---------------------------------------------------------

    product_name = models.CharField(
        max_length=155,
    )

    original_price_at_purchase = models.DecimalField(
        max_digits=10,
        decimal_places=2,
        default=Decimal("0.00"),
    )

    discount_percentage_at_purchase = models.DecimalField(
        max_digits=5,
        decimal_places=2,
        default=Decimal("0.00"),
    )

    price_at_purchase = models.DecimalField(
        max_digits=10,
        decimal_places=2,
        default=Decimal("0.00"),
    )

    quantity = models.PositiveIntegerField(
        validators=[
            MinValueValidator(1),
        ],
        default=1,
    )

    class Meta:
        ordering = ["id"]

    def subtotal(self):

        return (
            self.price_at_purchase *
            self.quantity
        )

    def save(self, *args, **kwargs):

        # Take the product snapshot only when the
        # OrderItem is first created.
        #
        # This prevents future product price/discount
        # changes from modifying historical orders.

        if self.product and self._state.adding:

            if not self.product_name:
                self.product_name = self.product.name

            self.original_price_at_purchase = (
                self.product.price
            )

            self.discount_percentage_at_purchase = (
                self.product.discount_percentage
            )

            self.price_at_purchase = (
                self.product.discounted_price
            )

        super().save(*args, **kwargs)

    def __str__(self):

        return (
            f"{self.quantity} × "
            f"{self.product_name} "
            f"(Order #{self.order_id})"
        )