# Generated by Django 4.2.30 on 2026-08-25 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('riders', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='riderprofile',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='riderprofile',
            name='vehicle_number',
        ),
        migrations.RemoveField(
            model_name='riderprofile',
            name='vehicle_type',
        ),
        migrations.RemoveField(
            model_name='riderprofile',
            name='verification_status',
        ),
        migrations.AddField(
            model_name='riderprofile',
            name='full_name',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='riderprofile',
            name='availability_status',
            field=models.CharField(choices=[('available', 'Available'), ('busy', 'Busy'), ('offline', 'Offline')], default='offline', max_length=10),
        ),
    ]
