# Generated by Django 4.2.30 on 2026-06-20 04:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerprofile',
            name='profile_picture',
            field=models.URLField(blank=True, default='https://ik.imagekit.io/fndgsrylj/Users/simple-user-default-icon-free-png.webp?updatedAt=1781789475953', null=True),
        ),
        migrations.AddField(
            model_name='sellerprofile',
            name='profile_picture',
            field=models.URLField(blank=True, default='https://ik.imagekit.io/fndgsrylj/Users/simple-user-default-icon-free-png.webp?updatedAt=1781789475953', null=True),
        ),
        migrations.AlterField(
            model_name='customerprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='customer_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='sellerprofile',
            name='business_document',
            field=models.URLField(),
        ),
        migrations.AlterField(
            model_name='sellerprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='seller_profile', to=settings.AUTH_USER_MODEL),
        ),
    ]
