# Generated by Django 4.2.30 on 2026-08-17 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_customerprofile_profile_picture_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('customer', 'Customer'), ('seller', 'Seller'), ('rider', 'Rider'), ('admin', 'Admin')], default='customer', max_length=20),
        ),
    ]
